2025-05-31 00:27:16,543 - selfimprove_logger_8677455936 - INFO - No existing container with name dgm-container-20250531_002716_506348 found.
2025-05-31 00:27:16,544 - selfimprove_logger_8677455936 - INFO - Building the Docker image...
Traceback (most recent call last):
  File "/Users/satoshinakamoto/Documents/AtlasInfinity/dgm/self_improve_step.py", line 449, in <module>
    main()
  File "/Users/satoshinakamoto/Documents/AtlasInfinity/dgm/self_improve_step.py", line 437, in main
    metadata = self_improve(
  File "/Users/satoshinakamoto/Documents/AtlasInfinity/dgm/self_improve_step.py", line 270, in self_improve
    container = build_dgm_container(
  File "/Users/satoshinakamoto/Documents/AtlasInfinity/dgm/utils/docker_utils.py", line 118, in build_dgm_container
    image, logs = client.images.build(path=repo_path, tag=image_name, rm=True)
  File "/Users/satoshinakamoto/Documents/AtlasInfinity/dgm/venv/lib/python3.10/site-packages/docker/models/images.py", line 296, in build
    resp = self.client.api.build(**kwargs)
  File "/Users/satoshinakamoto/Documents/AtlasInfinity/dgm/venv/lib/python3.10/site-packages/docker/api/build.py", line 263, in build
    response = self._post(
  File "/Users/satoshinakamoto/Documents/AtlasInfinity/dgm/venv/lib/python3.10/site-packages/docker/utils/decorators.py", line 44, in inner
    return f(self, *args, **kwargs)
  File "/Users/satoshinakamoto/Documents/AtlasInfinity/dgm/venv/lib/python3.10/site-packages/docker/api/client.py", line 242, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/Users/satoshinakamoto/Documents/AtlasInfinity/dgm/venv/lib/python3.10/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/Users/satoshinakamoto/Documents/AtlasInfinity/dgm/venv/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/satoshinakamoto/Documents/AtlasInfinity/dgm/venv/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/satoshinakamoto/Documents/AtlasInfinity/dgm/venv/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/Users/satoshinakamoto/Documents/AtlasInfinity/dgm/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "/Users/satoshinakamoto/Documents/AtlasInfinity/dgm/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 493, in _make_request
    conn.request(
  File "/Users/satoshinakamoto/Documents/AtlasInfinity/dgm/venv/lib/python3.10/site-packages/urllib3/connection.py", line 459, in request
    self.send(chunk)
  File "/Users/satoshinakamoto/.pyenv/versions/3.10.14/lib/python3.10/http/client.py", line 999, in send
    self.sock.sendall(data)
KeyboardInterrupt
